#!/usr/bin/python2

# BSD New Licence (c) 2012 Jonas Zetterberg

import sys
from gi.repository import Gtk, Notify, GLib

sys.path.append("/usr/share/pyshared/")

from Raptz import Raptz, RaptzError
from Raptz.ui.gtkui import GtkUI
from threading import Thread

def rt():
	debug = False
	ret = 1
	gui = GtkUI("raptz.log", win)
	try:
		raptz = Raptz(gui)
		debug = raptz.args.debug
		ret = raptz.start()
	except RaptzError, why:
		print ""
		print ""
		print "Failed to create sysroot: " + str(why)
	except KeyboardInterrupt:
		print ""
		print ""
		print "It looks like you have canceled the Sysroot installation. Installation is not complete."
	except BaseException,why:
		print ""
		print ""
		print "Got Base exception ", repr(why), ". Installation failed."
		if debug:
			raise
	except Exception, why:
		print ""
		print ""
		print "Got exception", repr(why), ". Installation failed."
		if debug:
			raise
	if gui.chk.get_active():
		Gtk.main_quit()
	return False

if __name__=="__main__":
	import signal
	signal.signal(signal.SIGINT, signal.SIG_DFL)
	win = Gtk.Window()
	win.set_title("raptz")
	win.set_default_geometry(640, 320)
	win.show_all()
	Thread(target=rt).start()
	Gtk.main()
	exit(0)
