#!/bin/bash

# Rapid apt 

set -e

. lib/common.inc
_common_root

# Print help
_help()
{
	echo ""
	echo "$(basename $0) [options]"
	echo ""
	echo "Clean a sysroot from raptz files"
	echo ""
	_common_help
	echo ""
	exit
}

LPIDS=$(ps -A -o pid,cmd h | grep -r "^[0-9]*\ /usr/bin/qemu-arm-static")
if [ -n "$LPIDS" ] ; then
	echo "Killing Left running pids that should have been killed:"
	echo $LPIDS
	kill $(echo $LPIDS | awk '{ print $1 }')
fi
_common_opts "-" $@
_common_ui
_common_chk_mount

rm -rf $RAPTZ_SYSROOT/etc/raptz
rm $RAPTZ_SYSROOT/multistrap.cfg

