#!/usr/bin/python

import sys
import os

from libraptz.host import Host
from libraptz.configuration import Configuration
from libraptz.cdebootstrap import CDebootstrap
from libraptz.debootstrap import Debootstrap
from libraptz.multistrap import Multistrap
from libraptz.apt import Apt
from libraptz.configure import Configure
from libraptz.raptzerror import RaptzException
import libraptz.comp as comp
#from libraptz.mount import Mount

# Should be moved to ui?
class Script:
	_script = []
	def __init__(self, host):
		self._host = host

	def add(self, cmd, *kargs):
		self._script.append((cmd, kargs))

	def run(self):
		self._host.set_parts(len(self._script))
		for cmd, kargs in self._script:
			self._host.start(cmd.__name__)
			cmd(*kargs)
			self._host.done()
		return True

from argparse import ArgumentParser
class Raptz:
	"""
Raptz sysroot handler

  raptz command [options]
	"""
	debug=True
	def __init__(self):
		self._argp = ArgumentParser(prog="raptz")

	def _parse_args(self):
		self._argp.add_argument('-p', '--path', default="sysroot",
			help="Path to sysroot"
		)
		self._argp.add_argument("--debug", default=False,
			action='store_true',
			help="Enable debug mode"
		)

		self._argp.add_argument('-n', '--name', default="default",
			help="Configuration name"
		)
		self._argp.add_argument('-l', '--logfile', default="raptz.log",
			help="Set logfile (default raptz.log)"
		)
		self._argp.add_argument('-u', '--ui', default="term",
			help="Ui selection (log, term)"
		)
		self._argp.add_argument('-m', '--mode', default="fake",
			help="Mode (fake or root)"
		)
		args = self._argp.parse_args()
		self.debug = args.debug
		self._conf = Configuration(args)

	def chroot(self):
		""" Chroot into a sysroot """
		try:
			i = sys.argv.index("--")
			cmds = sys.argv[i+1:]
			sys.argv = sys.argv[0:i]
		except ValueError:
			cmds=["bash"]
		self._parse_args()
		self._conf.args.ui = "log"
		host = Host(self._conf)
		host.fs.mount_system()
		ret = host.runner.chroot(cmds)
		host.fs.umount_system()
		return ret

	def tar(self):
		""" Create one or multiple compressed tar files """
		self._comp(comp.Tar)

	def cpio(self):
		""" Create one or multiple compressed cpio files """
		self._comp(comp.Cpio)

	def _comp(self, basetype):
		self._argp.add_argument("-t", "--tar", default=None,
			help="Create a uncompressed tar file")
		self._argp.add_argument("-g", "--gzip", default=None,
			help="Create a gzip compressed tar file")
		self._argp.add_argument("-b", "--bzip2", default=None,
			help="Create a bzip2 compressed tar file")
		self._argp.add_argument("-x", "--xz", default=None,
			help="Create a xz compressed tar file")
		self._parse_args()
		self._conf.args.ui = "log"
		host = Host(self._conf)
		tar = basetype(host)
		if self._conf.args.tar and self._conf.args.tar != "":
			tar.add(comp.Cat(self._conf.args.tar))
		if self._conf.args.gzip and self._conf.args.gzip != "":
			tar.add(comp.GZip(self._conf.args.gzip))
		if self._conf.args.bzip2 and self._conf.args.bzip2 != "":
			tar.add(comp.BZip2(self._conf.args.bzip2))
		if self._conf.args.xz and self._conf.args.xz != "":
			tar.add(comp.XZ(self._conf.args.xz))
		tar.compress()


	def mksys(self):
		""" Create a sysroot """
		self._argp.add_argument("-c", "--clean", help="Clean the sysroot before building",
			 default=False, action='store_true')
		self._argp.add_argument("-D", "--dev", help="Run development parts of configuration",
			 default=False, action='store_true')
		self._argp.add_argument("-S", "--suite", help="Set different suite to install",
			default=None)
		self._argp.add_argument("-b", "--bootstrap", default="multistrap",
			help="bootstrap mode (multstrap*, debootstrap, cdebootstrap)"
		)
		self._parse_args()
		host = Host(self._conf)
		sc = Script(host)
		if self._conf.args.bootstrap == "multistrap":
			bsp = Multistrap(host)
		elif self._conf.args.bootstrap == "debootstrap":
			bsp = Debootstrap(host)
		elif self._conf.args.bootstrap == "cdebootstrap":
			bsp = CDebootstrap(host)
		else:
			raise "Unknown mode " + self._conf.args.bootstrap
		apt = Apt(host)
		cfg = Configure(host)
		if self._conf.args.clean:
			sc.add(cfg.clean)
		sc.add(bsp.bootstrap)
		sc.add(cfg.debconf)
		sc.add(bsp.secondstage)
		sc.add(cfg.copyroot)
		sc.add(bsp.finalize)
		
		sc.add(host.fs.mount_system)
		sc.add(apt.update)
		sc.add(apt.install, self._conf.keyrings())
		sc.add(apt.update)
		sc.add(apt.install, self._conf.packages())
		sc.add(cfg.configure)
		sc.add(host.fs.umount_system)
		sc.run()
		return True

	def help(self):
		""" Print this help"""
		print self.__doc__
		print "Commands:"
		for m in dir(self):
			if m.startswith("_"):
				continue
			print "  %-10s - %s" %(m, getattr(self, m).__doc__)
		print ""

command="help"
try:
	command=sys.argv[1]
	del sys.argv[1]
except IndexError:
	pass

ret = 0
raptz = Raptz()
func = getattr(raptz, command)
try:
	if not func():
		ret = 1
except RaptzException as e:
	if raptz.debug:
		raise
	else:
		print
		print "ERROR: " + str(e)
		print
	exit(1)

try:
	os.wait()
except OSError as e:
	if e.errno == 10: # No child process
		pass
	else:
		raise
exit(ret)
