#!/bin/bash

# Rapid apt 

set -e

. lib/common.inc

# Print help
_help()
{
	echo ""
	echo "$(basename $0) [options] " 
	echo ""
	echo "Prepare and setup kernel"
	echo ""
	echo "Special options:"
	echo "   -d <path> Path to kernel source"
	echo "   -D        Prepare kernel headers"
	echo ""
	_common_opts
	echo ""
	exit
}


_common_opts "Dd:" $@
_common_ui

KERNELDIR=$RAPTZ_DEV
[ -d "$KERNELDIR" ] || _error "$KERNELDIR not found"

_headers()
{
	RAPTZDIR=$PWD/$RAPTZ_NAME/etc/raptz
	pushd $KERNELDIR
	make LOCALVERSION= ARCH=arm headers_install INSTALL_HDR_PATH=$RAPTZ_SYSROOT/usr
	popd
}

_modules()
{
	pushd $KERNELDIR
	make LOCALVERSION= ARCH=arm modules_install INSTALL_MOD_PATH=$RAPTZ_SYSROOT
	popd
}

if (( $RAPTZ_ADD_DEV == 1 )) ; then
	_headers | _log "Preparing kernel headers"
fi
_modules | _log "Preparing kernel modules"
echo ""
