#!/bin/bash

set -e
set -o pipefail

. lib/common.inc

# Print help
_help()
{
	echo ""
	echo "$(basename $0) [options]"
	echo ""
	echo "Run configuration scripts for target"
	echo ""
	echo "Command Options:"
	echo "  -D        Also install development files"
	echo "  -f        Force copying of extra enviroment"
	echo ""
	_common_help
	echo ""
	echo "Logfile is $RAPTZ_LOGFILE"
	echo ""
	exit
}

_common_opts "Df" $@
_common_ui
_common_chk_mount

# Install internal scripts
pushd $RAPTZ_NAME >> $RAPTZ_LOGFILE
TOT=$(find | wc -l)
for FILE in $(find) ; do
	echo $FILE
	if ( [ -e $RAPTZ_SYSROOT/$FILE ] && (( $RAPTZ_FORCE == 0 )) ) ; then
		continue
	fi
	if [ -f $FILE ] ; then
		mkdir -p $RAPTZ_SYSROOT/$(dirname $FILE) || true
		if $(dirname $FILE | grep "bin$" >/dev/null) ; then
			install -m 755 $FILE $RAPTZ_SYSROOT/$FILE
		else
			install $FILE $RAPTZ_SYSROOT/$FILE
		fi
	elif [ -d $FILE ] ; then
		mkdir -p $RAPTZ_SYSROOT/$FILE
	fi
done | _log_num $TOT "Installing extra"
popd >> $RAPTZ_LOGFILE


# Run internal scripts
for FILE in $(ls $RAPTZ_SYSROOT/etc/raptz/bin | sort -n) ; do
	if ( (( $RAPTZ_ADD_DEV == 0 )) && echo $FILE | grep "dev.sh$" > /dev/null  ) ; then
		continue
	fi
	./raptz-chroot /etc/raptz/bin/$FILE 2>&1 \
			| _log "Running $FILE"
done

