#!/bin/bash

set -e
set -o pipefail

. lib/common.inc

# Print help
_help()
{
	echo ""
	echo "$(basename $0) [options]"
	echo ""
	echo "Run configuration scripts for target"
	echo ""
	echo "Command Options:"
	echo "  -D        Also install development files"
	echo "  -f        Force copying of extra enviroment"
	echo ""
	_common_help
	echo ""
	echo "Logfile is $RAPTZ_LOGFILE"
	echo ""
	exit
}

_common_opts "Df" $@
_common_ui
_common_chk_mount

# Copy files if newer preserving links
N=$(find $RAPTZ_NAME/root/ | wc -l)
cp -v -u -d -r $RAPTZ_NAME/root/* $RAPTZ_SYSROOT | _log_num $N "Copying extra root files"

# setup configuration
CONF_DIR=$RAPTZ_NAME/conf
CONF_POINT=$(mktemp -d --tmpdir=$RAPTZ_SYSROOT/tmp/)
CONF_CHPATH=/tmp/$(basename $CONF_POINT)

for DIR in $(ls -p $CONF_DIR | grep "^[0-9][0-9].*\/$" | sort -n); do
	# For each script mount it in /tmp and run init.sh and init.dev.sh if avalible
	cp -r $CONF_DIR/$DIR/* $CONF_POINT
	
	if [ -f $CONF_POINT/init.sh ] ; then
		./raptz-chroot $CONF_CHPATH/init.sh $CONF_CHPATH 2>&1 | \
			_log "Running configuration ${DIR}"
	fi 

	if (( $RAPTZ_ADD_DEV )) ; then
		if [ -f $CONF_POINT/init.dev.sh ] ; then
		./raptz-chroot $CONF_CHPATH/init.dev.sh $CONF_CHPATH 2>&1 | \
			_log "Runnint development configuration ${DIR}"
		fi 
	fi
	rm -rf $CONF_POINT/*
done
rmdir $CONF_POINT

exit

