#!/bin/bash

# Rapid apt 

set -e
set -o pipefail

. lib/common.inc

# Print help
_help()
{
	echo ""
	echo "$(basename $0) [options]"
	echo ""
	echo "Options:"
	echo "  -c        Clean SYSROOT"
	echo "  -s        Skip multistrap stage"
	echo ""
	_common_help
	echo ""
	echo "Logfile is $RAPTZ_LOGFILE"
	echo ""
	exit
}

_common_opts "cs" $@
_common_ui
_common_chk_mount

# Clean sysroot
if (( $RAPTZ_CLEAN == 1 )) ; then
	TOT=$(find $RAPTZ_SYSROOT | wc -l)
	rm -rvf $RAPTZ_SYSROOT | \
		_log_num $TOT "Cleaning $RAPTZ_SYSROOT"
fi

# Do the multistrap
(( $RAPTZ_SKIP == 0 )) && \
	multistrap -f $RAPTZ_NAME/multistrap.cfg -d $RAPTZ_SYSROOT 2>&1 | \
		_log "Multistrapping $RAPTZ_NAME.cfg into $RAPTZ_SYSROOT"

