#!/bin/bash

# Rapid apt 

set -e

. lib/common.inc

# Print help
_help()
{
	echo ""
	echo "$(basename $0) [options] [path-to-kernel-source-root]"
	echo ""
	echo "Prepare and include klernel headers"
	echo ""
	_common_opts
	echo ""
	exit
}


_common_opts "-" $@
_common_ui

KERNELDIR=$1
[ -d "$KERNELDIR" ] || _error "$KERNELDIR not found"

_headers()
{
	RAPTZDIR=$PWD/$RAPTZ_NAME/etc/raptz
	pushd $KERNELDIR
	TMPDIR=$(mktemp -d)
	make ARCH=arm headers_install INSTALL_HDR_PATH=$TMPDIR
	popd
	pushd $TMPDIR
	tar czf $RAPTZDIR/headers.tar.gz .
	popd
	rm -r $TMPDIR
	
	cat > $RAPTZDIR/bin/40kernelheaders.dev.sh <<EOF
#!/bin/dash
set -e
cd /usr
tar xzf /etc/raptz/headers.tar.gz
chmod 755 .
EOF
}

_modules()
{
	MODDIR=$PWD/$RAPTZ_NAME
	pushd $KERNELDIR
	make ARCH=arm modules_install INSTALL_MOD_PATH=$MODDIR
	popd
}
_headers | _log "Preparing kernel headers"
_modules | _log "Preparing kernel modules"
