#!/bin/bash

mode=fake
if [ "$(whoami)" = "root" ]; then
	mode=root
fi
set -e

mkdir -p tst$mode
_test()
{
	sys=tst$mode/$1
	echo "$sys mkroot"
	./raptz mkroot $sys -n sid -b $1 -m $mode -u log >${sys}.mkroot.log 2>&1
	echo "$sys cpio"
	./raptz cpio $sys -x ${sys}.cpio.xz 
	echo "$sys tar"
	./raptz tar $sys -r ${sys}.tar -g ${sys}.tar.gz -b${sys}.tar.bz2
	echo "$sys chroot pipe"
	RET=$(echo "echo ok1" | ./raptz chroot $sys)
	[ "$RET" = "ok1" ]
	echo "$sys chroot dash dash"
	RET=$(./raptz chroot $sys -- echo ok2)
	[ "$RET" = "ok2" ]
	echo "$sys chroot return"
	./raptz chroot $sys -- bash -c "exit 42" || RET=$?
	[ "$RET" = 42 ]
}

_test cdebootstrap &
_test debootstrap &
_test multistrap &

while [ -n "$(jobs)" ] ; do
	wait -n || RET=1
	jobs
	if [ "$RET" != "0" ] ; then
		RET=$(( RET++ ))
	fi
done
if [ "$RET" != "0" ] ; then
	echo "failed"
	false
fi
rm -rf tst$mode
