#!/bin/bash

set -e


mkdir -p testroot
_test()
{
	sys=testroot/$1
	echo "$sys mksys"
	./raptz mksys -n sid -p $sys -b $1 -m root -u log >${sys}.mksys.log 2>&1
	echo "$sys cpio"
	./raptz cpio -n sid -p $sys -x ${sys}.cpio.xz
	echo "$sys tar"
	./raptz tar -n sid -p $sys -r ${sys}.tar -g ${sys}.tar.gz -b${sys}.tar.bz2
	echo "$sys chroot pipe"
	RET=$(echo "echo ok1" | ./raptz chroot -n sid -p $sys -m root)
	[ "$RET" = "ok1" ]
	echo "$sys chroot dash dash"
	RET=$(./raptz chroot -n sid -p $sys -m root -- echo ok2)
	[ "$RET" = "ok2" ]
	echo "$sys chroot return"
	./raptz chroot -n sid -p $sys -m root -- bash -c "exit 42" || RET=$?
	[ "$RET" = 42 ]
}

_test cdebootstrap &
_test debootstrap &
_test multistrap &

while [ -n "$(jobs)" ] ; do
	jobs
	echo
	wait -n || RET=1
	if [ "$RET" != "0" ] ; then
		RET=$(( RET++ ))
	fi
done
if [ "$RET" != "0" ] ; then
	echo "failed"
	false
fi
rm -rf testroot
